### ISSUE TITLE
Prepare for Caddy 2

### ISSUE THREAD

**Issue by serverwentdown** [productionwentdown/caddy#8]
### Goals
Become a frequently updated minimal containerisation of Caddy, binary-only

### TODO
- [x] Test that a binary-only image can be built
  - [x] `ldd caddy` says `not a dynamic executable` :tada: 
  - [x] If caddy-docker is already statically linked, can use `COPY --from=` and have a very tiny Dockerfile :smile:
- [ ] Add warnings about minimal containers
- [ ] Become a clone of the [official image](https://github.com/caddyserver/caddy-docker) with matrix builds
- [ ] Automate build based on caddy-docker (scheduled task?)

**Comment by serverwentdown** [comment]
Test image available at `productionwentdown/caddy:test`. 8.66MB is compressed enough!

```
FROM caddy/caddy:2.0.0-rc.1 as build

RUN apk add --no-cache upx ca-certificates \
    && upx --ultra-brute /usr/bin/caddy \
    && caddy version

FROM scratch

COPY --from=build /etc/caddy/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /usr/share/caddy/index.html /usr/share/caddy/index.html
COPY --from=build /usr/bin/caddy /usr/bin/caddy
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENV XDG_CONFIG_HOME=/config
ENV XDG_DATA_HOME=/data
ENV HOME=/

VOLUME /config
VOLUME /data

LABEL org.opencontainers.image.version=v2.0.0-rc.1
LABEL org.opencontainers.image.title="Caddy (productionwentdown)"
LABEL org.opencontainers.image.description="a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go"
LABEL org.opencontainers.image.url=https://productionwentdown.github.io
LABEL org.opencontainers.image.documentation=https://caddyserver.com/docs
LABEL org.opencontainers.image.vendor="productionwentdown"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.source="https://github.com/productionwentdown/caddy"

EXPOSE 80
EXPOSE 443
EXPOSE 2019

ENTRYPOINT ["/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
```
